### ISSUE TITLE
postfixadmin assumes mysql database is running on localhost

### ISSUE THREAD

**Issue by stevehu** [hardware/postfixadmin#15]
I have mysql database running on another server with xx.xx.xx.187 and postfixadmin running on xx.xx.xx.186.

In docker-compose.yml I have the following postfixadmin service.

```
  postfixadmin:
    image: hardware/postfixadmin
    container_name: postfixadmin
    domainname: domain.tld
    hostname: mail
    restart: always
    ports:
      - 8888:8888
    environment:
      - "DBHOST=xx.xx.xx.187"
      - "DBPORT=3306"
      - "DBNAME=postfix"
      - "DBUSER=postfix"
      - "DBPASS=password"
    depends_on:
      - mailserver
```

However I got the following error on setup.php

```
Error: Can't connect to database
Please edit the $CONF['database_*'] parameters in config.local.php.
DEBUG INFORMATION:
Connect: Access denied for user 'postfix'@'xx.xx.xx.186' (using password: YES)
```

The config.local.php inside the container is correct with xx.xx.xx.187

```
$CONF['database_type'] = 'mysqli';                                                                                                                                             
$CONF['database_host'] = 'xx.xx.xx.187';                                                                                                                                      
$CONF['database_user'] = 'postfix';                                                                                                                                            
$CONF['database_password'] = 'password';                                                                                                                                       
$CONF['database_name'] = 'postfix';     
```
I am wondering if there are somewhere hard-coded db host as localhost? I am not a php guy and couldn't  figure out myself. Thanks.
