### ISSUE TITLE
Error: Depends on: multibyte string - NOT FOUND

### ISSUE THREAD

**Issue by MisterCyp** [hardware/postfixadmin#3]
Salut Hardware,

J'ai suivi ton tuto pour l'installation via docker mais j'ai quelques soucis lorsque je vais sur la page postfixadmin.domain.tld/setup.php : 

![image](https://cloud.githubusercontent.com/assets/12878314/15263679/7544f736-196c-11e6-9aac-244f1a592c8e.png)

Et lorsque je lance la commande suivante : 

`docker exec -ti postfixadmin sh setup`

> sh: can't open 'setup'

Enfin lorsque je souhaite me loguer sur la page postfixadmin.domain.tld/login.php
Voici la réponse, il y a un problème avec la base de données : 

> Invalid query: Table 'postfix.domain' doesn't exist
> Check your error_log for the failed query.

```
  mailserver:
    image: hardware/mailserver
    container_name: mailserver
    domainname: mondomaine
    hostname: mail
    links:
      - db-mail:mariadb
    ports:
      - "25:25"     # SMTP                - Required
      - "143:143"   # IMAP       STARTTLS - For webmails/desktop clients
      - "465:465"   # SMTPS      SSL/TLS  - Enabled for compatibility reason, otherwise disabled
      - "587:587"   # Submission STARTTLS - For webmails/desktop clients
      - "993:993"   # IMAPS      SSL/TLS  - For webmails/desktop clients
      - "4190:4190" # SIEVE      STARTTLS - Optional, but recommended for mail filtering
    environment:
      - DBPASS=monMDP
    volumes:
      - /home/cyprien/docker/containers/mail:/var/mail
      - /home/cyprien/docker/containers/opendkim:/etc/opendkim/keys

  # Control panel
  postfixadmin:
    image: hardware/postfixadmin
    container_name: postfixadmin
    domainname: mondomaine
    hostname: mail
    links:
      - db-mail:mariadb
    environment:
      - DBPASS=monMDP

  # Webmail
  rainloop:
    image: hardware/rainloop
    container_name: rainloop
    links:
      - mailserver:mailserver
      - db-mail:mariadb
    volumes:
      - /home/cyprien/docker/containers/rainloop:/rainloop/data

  # Database
  db-mail:
    image: mariadb:10.1
    container_name: db-mail
    environment:
      - MYSQL_ROOT_PASSWORD=monMDP
      - MYSQL_DATABASE=postfix
      - MYSQL_USER=postfix
      - MYSQL_PASSWORD=monMDP
    volumes:
      - /home/cyprien/docker/containers/mysql/db:/var/lib/mysql
```

Merci pour ton travail ;)
