### ISSUE TITLE
nginx not running

### ISSUE THREAD

**Issue by tflori** [hardware/postfixadmin#5]
supervise tries to start nginx every second but it does not start:

```
2017/02/16 09:24:54 [emerg] 775#0: open() "/var/lib/nginx/logs/error.log" failed (13: Permission denied)
nginx: [alert] could not open error log file: open() "/var/lib/nginx/logs/error.log" failed (13: Permission denied)
```

I don't understand where is the problem - I checked the permissions and all files theme to be owned by 991 with the correct permissions. Even with permissions 0666 on /var/lib/nginx/logs/error.log nginx can not start.

Some console output:
```
/var/log # ls -lahR
.:
total 16
drwxrwxrwx    6 991      991         4.0K Feb 16 06:21 .
drwxrwxrwx   17 root     root        4.0K Feb 16 06:21 ..
drwxrwxrwx    2 991      991         4.0K Feb 16 06:53 nginx
drwxr-xr-x    2 991      991         4.0K Feb 16 06:21 php7

./nginx:
total 12
drwxrwxrwx    2 991      991         4.0K Feb 16 06:53 .
drwxrwxrwx    6 991      991         4.0K Feb 16 06:21 ..
-rw-rw-rw-    1 991      991            1 Feb 16 09:21 error.log

./php7:
total 12
drwxr-xr-x    2 991      991         4.0K Feb 16 06:21 .
drwxrwxrwx    6 991      991         4.0K Feb 16 06:21 ..
-rw-------    1 991      991          531 Feb 16 09:18 error.log
```

And the service config from my docker-compose.yml
```yml
version: '2'
services:
  postfixadmin:
    image: hardware/postfixadmin
    domainname: domain.tld
    hostname: mail
    restart: always
    environment:
      - 'DBPASS=xxx'
    depends_on:
      - mailserver
      - mariadb
    networks:
      - back
```

Am I missing something or is your image broken?
