### ISSUE TITLE
Getting error about module loading mysqlnd.so

### ISSUE THREAD

**Issue by maZahaca** [hardware/postfixadmin#7]
[20-Feb-2017 15:48:24] NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7.1/modules/mysqlnd.so' - Error relocating /usr/lib/php7.1/modules/mysqlnd.so: BIO_new_mem_buf: symbol not found in Unknown on line 0

Started this with docker-compose.yml:
```yml
postfixadmin:
  image: hardware/postfixadmin
  container_name: postfixadmin
  domainname: domain.ltd
  hostname: mail
  restart: always
  environment:
    - DBPASS=xxxxxxxxxx
  links:
    - mailserver
    - mariadb
```
